### ISSUE TITLE
dockerで環境構築

### ISSUE THREAD

**Issue by takanori-matsushita** [takanori-matsushita/BFF-practice#1]
Rails・DBはdockerで構築。
Nuxt.jsはローカル環境で構築。

**Comment by takanori-matsushita** [comment]
以下の記事を参考にDockerで環境構築する
[[参考]DockerでRailsの環境構築](https://qiita.com/kodai_0122/items/795438d738386c2c1966)

**Comment by takanori-matsushita** [comment]
今回RailsではViewを使用しないためAPIモードで作成する。
参考リンク`2. プロジェクトのビルド`のところのコマンドは以下のもので実行する。
`docker-compose run web rails new --api . --force --no-deps --database=postgresql --skip-bundle`

**Comment by takanori-matsushita** [comment]
Database is uninitialized and superuser password is not specified.
エラーが発生。データベースのパスワードを設定しないといけないっぽい。

docker-compose.yml
```
version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
#passwordここから
    environment:
      POSTGRES_PASSWORD: password
#passwordここまで
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
```
